apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: <HPA>
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: <NAME>
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: AverageValue
          averageValue: <CPU>m
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: '<MEM>'
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 120
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Pods
          value: 2
          periodSeconds: 30
